/**
 * Blocklist of disposable/temporary email domains.
 * These are commonly used to abuse free tiers.
 */

const DISPOSABLE_DOMAINS = new Set([
	// Common disposable email services
	'10minutemail.com',
	'10minutemail.net',
	'tempmail.com',
	'tempmail.net',
	'temp-mail.org',
	'temp-mail.io',
	'guerrillamail.com',
	'guerrillamail.org',
	'guerrillamail.net',
	'guerrillamail.biz',
	'guerrillamail.de',
	'guerrillamailblock.com',
	'sharklasers.com',
	'grr.la',
	'pokemail.net',
	'spam4.me',
	'mailinator.com',
	'mailinator.net',
	'mailinator.org',
	'mailinator2.com',
	'mailinater.com',
	'throwawaymail.com',
	'throwaway.email',
	'fakeinbox.com',
	'fakemailgenerator.com',
	'getnada.com',
	'nada.email',
	'tempinbox.com',
	'dispostable.com',
	'mailnesia.com',
	'maildrop.cc',
	'mintemail.com',
	'mohmal.com',
	'yopmail.com',
	'yopmail.fr',
	'yopmail.net',
	'cool.fr.nf',
	'jetable.fr.nf',
	'courriel.fr.nf',
	'moncourrier.fr.nf',
	'monemail.fr.nf',
	'monmail.fr.nf',
	'emailondeck.com',
	'getairmail.com',
	'trashmail.com',
	'trashmail.net',
	'trashmail.org',
	'trashmail.me',
	'trashemail.de',
	'wegwerfmail.de',
	'wegwerfmail.net',
	'wegwerfmail.org',
	'mytrashmail.com',
	'mt2009.com',
	'thankyou2010.com',
	'trash2009.com',
	'mt2014.com',
	'tempsky.com',
	'spamgourmet.com',
	'spamgourmet.net',
	'spamgourmet.org',
	'mailexpire.com',
	'tempemailaddress.com',
	'spambox.us',
	'spamfree24.org',
	'spamfree24.de',
	'spamfree24.info',
	'spamfree24.eu',
	'spamobox.com',
	'anonymbox.com',
	'emailthe.net',
	'brefmail.com',
	'mailcatch.com',
	'kasmail.com',
	'inboxalias.com',
	'sofimail.com',
	'spam.la',
	'spaml.com',
	'spaml.de',
	'no-spam.ws',
	'spam.su',
	'spamoff.de',
	'emailsensei.com',
	'spamherelots.com',
	'devnullmail.com',
	'letthemeatspam.com',
	'thisisnotmyrealemail.com',
	'dodgeit.com',
	'dodgit.com',
	'dodgit.org',
	'e4ward.com',
	'gishpuppy.com',
	'mailzilla.com',
	'mailzilla.org',
	'sneakemail.com',
	'spamex.com',
	'spammotel.com',
	'mailnull.com',
	'mail-temporaire.fr',
	'ephemail.net',
	'lortemail.dk',
	'filzmail.com',
	'mailscrap.com',
	'dontmail.me',
	// The domain from the report
	'uiemail.com',
	// More disposable domains
	'disposableemailaddresses.emailmiser.com',
	'mailimate.com',
	'tempomail.fr',
	'discard.email',
	'discardmail.com',
	'discardmail.de',
	'spambog.com',
	'spambog.de',
	'spambog.ru',
	'0815.ru',
	'hulapla.de',
	'teleworm.us',
	'zetmail.com',
	'33mail.com',
	'maileater.com',
	'mailmoat.com',
	'spam.care',
	'notmailinator.com',
	'veryrealemail.com',
	'veryrealmail.com',
	'zoemail.com',
	'zomail.com',
	'spamevader.com',
	'emailias.com',
	'mailfreeonline.com',
	'instant-mail.de',
	'herp.in',
	'dingbone.com',
	'fudgerub.com',
	'lookugly.com',
	'smellfear.com',
	'tempr.email',
	'disbox.org',
	'disbox.net',
	'mailsac.com',
	'inboxkitten.com',
	'emailfake.com',
	'fakemailgenerator.net',
	'crazymailing.com',
	'tempmailo.com',
	'tempmailaddress.com',
	'burnermail.io',
	'mailpoof.com',
]);

/**
 * Check if an email address is from a disposable email service.
 */
export function isDisposableEmail(email: string): boolean {
	const domain = email.toLowerCase().split('@')[1];
	if (!domain) return false;
	return DISPOSABLE_DOMAINS.has(domain);
}

/**
 * Get the domain from an email address.
 */
export function getEmailDomain(email: string): string {
	return email.toLowerCase().split('@')[1] || '';
}
